[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "2nT8HjQ7KkqNycxE6iBYDKNiXmkF7TFzCo8h9tF7st11"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bryan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
